### ISSUE TITLE
SIGSEGV when trying to work with other versions of Oodle DLL

### ISSUE THREAD

**Issue by andrewathalye** [McSimp/linoodle#4]
When trying to use Oodle 2.9 or 2.3, I get Segmentation Faults. I'm afraid I don't have a good way to debug this since it looks to be in the Oodle DLL itself, but I'd be glad to use gdb / lldb and look into it further if you have any advice on doing so.

I'm using linoodle right now for a Destiny 2 file extractor that works on Linux, and it works very well except for occasional files, which I believe fail due to expecting a different Oodle version for decompression.

**Comment by McSimp** [comment]
Could you please link me to Oodle DLL you're trying to use and an example file that causes the segfault?

**Comment by andrewathalye** [comment]
[bad_file.zip](https://github.com/McSimp/linoodle/files/8514245/bad_file.zip)
[good_file.zip](https://github.com/McSimp/linoodle/files/8514246/good_file.zip)
[oo2core_3_win64.dll.zip](https://github.com/McSimp/linoodle/files/8514247/oo2core_3_win64.dll.zip)

I've done some more testing, and it looks like Oodle 2.3 works when using "good_file", but crashes with SIGSEGV on "bad_file". To test these files:
fread them directly into a buffer after unzipping.
 src_len = unzipped size of file
dst_len = 0x40000

I can confirm that both files are handled by oo2core_3_win64.dll on Windows, but the "bad_file" causes crashes on Linux.

The exact code I am using can be found in the attached .c.txt file.
[work.c.txt](https://github.com/McSimp/linoodle/files/8514281/work.c.txt)

Edit:
As best as I can tell, these files use one of the LZ_ compressors. Ooz is unable to decompress them, and I'm not sure how to use the LZNA code, since it doesn't have any obvious entrypoints.

Edit 2:
Both files look like LZH or OodleFormat.None (based upon the naming in OodleCS). They start 8C 07.

Edit 3:
They are definitely LZH. In theory they should be supported by up to oo2core_8_win64.dll. I found a native Linux x64 version of oodle 2.9, but that was after LZH support was dropped so it sadly does not help here.

**Comment by McSimp** [comment]
The crash was occurring because Oodle was calling `OutputDebugStringA` which I hadn't implemented. I've added an implementation on master which will stop it from crashing on `bad_file`: https://github.com/McSimp/linoodle/commit/90b8d825f7f89272f03f52b5d1db4708e07eb83f

I don't think `bad_file` is actually being decompressed correctly on Windows either. In the debug output on Windows I get the same as I now do on Linux, and `OodleLZ_Decompress` returns 0 on both as well:

```
OODLE ERROR : LZ corruption : not enough comp buf
OODLE ERROR : LZ corruption : bad decode len
```

**Comment by andrewathalye** [comment]
Thanks for looking into it. GDB couldn't help me since it didn't know anything about the pe-parsed library. I think the correct length for bad_file is actually less than 0x40000, but the format I'm unpacking it from doesn't encode that, so we use 0x40000 as a "safe" value. I'll check 90b8d82, but that would make sense.

**Comment by andrewathalye** [comment]
I've just checked, and can confirm that appears to be the problem. The real output size is 163840 instead of 262144, but the pkg files Destiny uses encode 262144 byte chunks for files and have a mechanism to remove any garbage data before outputting the actual file. Thank you for fixing it so quickly! I also get to see Oodle warning messages now, which is nice.

**Comment by McSimp** [comment]
No worries, happy to help!
